#!/bin/sh

NAME="restore.sh"
DAEMON="/usr/bin/${NAME}"

start()
{
	echo "0" > /sys/class/leds/led0/brightness
	echo "0" > /sys/class/leds/led1/brightness

	while [ ! -b /dev/mmcblk0p1 ]
	do
		sleep .5
	done

	echo "Loading sound configuration..."
	mcopy -t -n -D o -i /dev/mmcblk0p1 ::config/asound.state /var/lib/alsa/asound.state

	echo "Loading key..."
	mcopy -D o -n -i /dev/mmcblk0p1 ::config/key /etc/key

	echo "Loading crypto configuration..."
	cp /etc/crypto.ini /etc/crypto.ini.all && mcopy -t -n -D o -i /dev/mmcblk0p1 ::config/crypto.ini /etc/crypto.ini.sd && cat /etc/crypto.ini /etc/crypto.ini.sd > /etc/crypto.ini.all

	echo "Done"

	start-stop-daemon -S -b -q -x "${DAEMON}"
}

case "$1" in
	start|restart|reload)
		start
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
