#!/bin/sh

NAME="jackd_tx"
DAEMON="/usr/bin/start_jackd_tx.sh"

. /etc/profile.d/shell_functions.sh

start()
{
	wait_initialized

	ENABLE_LOG=`get_config_val Diagnostics EnableJACKLogging`

	if test "$ENABLE_LOG" = "1"
	then
		LOG_ARGS="-o /var/log/jackd_tx.log"
	fi

	printf "Starting ${NAME}: "
	daemon -n ${NAME} -r -L 15 $LOG_ARGS "${DAEMON}"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
	printf "Stopping ${NAME}: "
	if daemon --stop -n ${NAME}
	then
		while daemon --running -n ${NAME}
		do
			sleep .1
		done
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
