#!/bin/sh

NAME="jackd_tx"
DAEMON="/usr/bin/start_jackd_tx.sh"

. /etc/profile.d/shell_functions.sh

start()
{
	LOG_ARGS="-O daemon.info -E daemon.err"

	printf "Starting ${NAME}: "
	daemon -n ${NAME} -r -L 15 $LOG_ARGS "${DAEMON}"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
	printf "Stopping ${NAME}: "
	if daemon --stop -n ${NAME}
	then
		echo "OK"
	else
		echo "FAIL"
	fi
}

running()
{
	exec daemon --running -n ${NAME}
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	running)
		running
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
