#!/bin/sh

NAME="log2speech_rx"
DAEMON="/usr/bin/log_crypto_service.sh"
LOG_FILE="/var/log/crypto_rx.log"
PID_FILE="/var/run/${NAME}.pid"

start()
{
	printf "Starting ${NAME}: "
	start-stop-daemon -S -b -m -p "${PID_FILE}" -q -x "${DAEMON}" -- ${LOG_FILE}
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
	printf "Stopping ${NAME}: "
	if start-stop-daemon -K -q -s TERM -p "${PID_FILE}"; then
		rm -f "${PID_FILE}"
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
