#!/bin/sh

start()
{
	echo "Loading sound configuration..."
	mcopy -t -i /dev/mmcblk0p1 ::config/asound.state /var/lib/alsa/asound.state

	echo "Loading key..."
	mcopy -i /dev/mmcblk0p1 ::config/key /etc/key

	echo "Loading crypto configuration..."
	mcopy -t -i /dev/mmcblk0p1 ::config/crypto_tx.ini /etc/crypto_tx.ini
	mcopy -t -i /dev/mmcblk0p1 ::config/crypto_rx.ini /etc/crypto_rx.ini

	echo "Done"
}

case "$1" in
	start|restart|reload)
		start
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
