#!/bin/sh

NAME="jackd_rx"
DAEMON="/usr/bin/start_jackd_rx.sh"

start()
{
	while [ ! -e /var/run/initialized ]
	do
		inotifywait -qq -t 1 --include initialized -e create /var/run/
	done

	ENABLE_LOG=`iniget Diagnostics EnableJACKLogging /etc/crypto.ini.sd /etc/crypto.ini`

	if [ "$ENABLE_LOG" = "1" ]
	then
		LOG_ARGS="-o /var/log/jackd_rx.log"
	fi

	printf "Starting ${NAME}: "
	daemon -n ${NAME} -r -L 15 $LOG_ARGS "${DAEMON}"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
	printf "Stopping ${NAME}: "
	if daemon --stop -n ${NAME}; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
